export const SECURITY_EVENTS = {
  BODY_TOO_LARGE: "SECURITY_BODY_TOO_LARGE",
  INVALID_CONTENT_TYPE: "SECURITY_INVALID_CONTENT_TYPE",
  ORIGIN_REJECTED: "SECURITY_ORIGIN_REJECTED",
  RATE_LIMITED: "SECURITY_RATE_LIMITED",
  INVALID_JSON: "SECURITY_INVALID_JSON",
  INPUT_REJECTED: "SECURITY_INPUT_REJECTED",
  PAYMENT_SIGNATURE_INVALID: "PAYMENT_SIGNATURE_INVALID",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_REPLAYED: "PAYMENT_REPLAYED",
  ORDER_STOCK_REJECTED: "ORDER_STOCK_REJECTED",
  ORDER_REPLAYED: "ORDER_REPLAYED",
  PROVIDER_VERIFICATION_FAILED: "PROVIDER_VERIFICATION_FAILED",
} as const;

export type SecurityEvent = (typeof SECURITY_EVENTS)[keyof typeof SECURITY_EVENTS];
